### ISSUE TITLE
Using multiple resources in a ResourceSet gives invalid output

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#55] opened 2019-03-11 13:31 UTC
I'm experimenting with StringURI to get an intermediate string representation of a resource and run into a problem when serializing to disk.

I do the following:

1. I load an existing XML resource from file.
2. I want to store this as a String resource (using the documented StringURI). I get a valid representation as a string in python.
3. I do a resource.save() on the file resource loaded in (1). I get invalid output. 
4. If I create a new file resource I get valid output again.

Somehow the string resource saving corrupts the original one when it comes to references. 

This is what I input:
```
      <asset xsi:type="esdl:ElectricityDemand" id="e_demand_1" name="E demand">
        <port xsi:type="esdl:InPort" id="InPort1" connectedTo="OutPort1"/>
      </asset>
```
This is what i get:
```
      <asset xsi:type="esdl:ElectricityDemand" name="E demand" id="e_demand_1">
        <port xsi:type="esdl:InPort" id="InPort1">
          <connectedTo href="anyname#OutPort1" xsi:type="esdl:OutPort"/>
        </port>
      </asset>
```
My String URI was named ```anyname```

Any clues?

_Note: I adapted the StringURI to use io.BytesIO instead of io.StringIO, as lxml compained about bytes in Python 3.7_

**Comment by aranega** [comment] 2019-03-12 09:54
@ewoudwerkman Thanks for the report! I will try this asap. The thing that is generated is a proxy. Usually the resource does that when it sees that one of the elements comes from another resource than the one which is being serialized. In that case, it creates a reference to it. I probably introduced something fishy at some point, or there is a special case. I will check that!

Sorry for the inconvenience...

**Comment by aranega** [comment] 2019-03-12 11:28
@ewoudwerkman I tried to reproduce your bug, but everything works on my side. Clearly, there is something I forgot or I missed. Could you provide your input model? 

I tested this way: 

1. I load an `.esdl` XMI file in a resource using a `ResourceSet`
1. I create a `StringURI` (modified with `BytesIO` as you said)
1. I save the resource in the new created URI (using `resource.save(uri)`)
1. I then save again the resource back using `resource.save()`

I get the right output. In the whole process I always use the same `Resource`. Are you creating a new one for using the `StringURI`?

Is your model having multiple roots? Or only one?

**Comment by ewoudwerkman** [comment] 2019-03-13 16:38
@aranega I did create a new resource to save it as a string. Your approach with ```resource.save(uri)``` using the same resource, fixes this issue. 
I have a single root.

What I did was:
``` python
   def get_as_string(self):
        # to use strings as resources, we simulate a string as being a file
        uri = StringURI('anyname.esdl')
        # create the string resource
        stringresource = self.rset.create_resource(uri)
        # add the current energy system
        stringresource.append(self.es)
        # save the resource
        stringresource.save()
        # remove the temporary resource in the resource set
        self.rset.remove_resource(stringresource)
        # return the string
        return uri.getvalue()
```
Why is this approach going wrong?


My StringURI is like this:
``` python
class StringURI(URI):
    def __init__(self, uri, text=None):
        super(StringURI, self).__init__(uri)
        if text is not None:
            self.__stream = BytesIO(text.encode('UTF-8'))

    def getvalue(self):
        readbytes = self.__stream.getvalue()
        # somehow stringIO does not work, so we use BytesIO
        string = readbytes.decode('UTF-8')
        return string

    def create_instream(self):
        return self.__stream

    def create_outstream(self):
        self.__stream = BytesIO()
        return self.__stream
```
Any idea why StringIO does not work? lxml is at verision 4.2.4. I see there is a newer version but the changelogs don't mention StringIO issues. Python is at 3.7.14

**Comment by aranega** [comment] 2019-03-16 22:04
Sorry for the delay @ewoudwerkman.

I tried this script and I wasn't able to make the error appear. Did this script reproduce the error on your side? Perhaps I have something in my environment that fixes the XMI serialization:

```python
from pyecore.resources import ResourceSet, URI
import esdl
from io import BytesIO


class StringURI(URI):
    def __init__(self, uri, text=None):
        super(StringURI, self).__init__(uri)
        if text is not None:
            self.__stream = BytesIO(text.encode('UTF-8'))

    def getvalue(self):
        readbytes = self.__stream.getvalue()
        # somehow stringIO does not work, so we use BytesIO
        string = readbytes.decode('UTF-8')
        return string

    def create_instream(self):
        return self.__stream

    def create_outstream(self):
        self.__stream = BytesIO()
        return self.__stream


rset = ResourceSet()
rset.metamodel_registry[esdl.nsURI] = esdl

resource = rset.get_resource('test.esdl')
root = resource.contents[0]


uri = StringURI('anyname.esdl')
stringresource = rset.create_resource(uri)
stringresource.append(root)
stringresource.save()
rset.remove_resource(stringresource)


print(uri.getvalue())
```

**Comment by ewoudwerkman** [comment] 2019-11-18 16:29
I think this problem is based on creating an StringURI-based resource, which was unintendedly added to the ResourceSet, and therefore pyecore assumed it was a new resource and updated the references accordingly (and correctly). 

We did not run into this issue anymore, so you can close this issue.

**Comment by aranega** [comment] 2019-11-18 17:27
@ewoudwerkman I'm glad the issue is not here anymore :) I'm closing the PR. Thanks again!

**Closed by aranega** 2019-11-18 17:27 UTC
