### ISSUE TITLE
Resource loading problem with XMI referring to elements from different Ecore files

### ISSUE THREAD

**Issue by stefanq** [pyecore/pyecore#72] opened 2019-10-07 13:38 UTC
Hi,
we have a meta model being represented by two Ecore files.
In the top-level Ecore a class Project aggregates just one element which is of a class defined in the second Ecore. When serializing such a model in Eclipse, the child of the Project instance will have no xsi:type attribute.
However, when serializing such model from pyecore it has an xsi:type attribute.
According to the XMI standard, the xsi:type attribute is only required, if the type of the child is ambiguous, which is not the case here.
I.e. the pyecore XMI serialization in this respect is not conform with  the XMI standard.

The major problem with this is interoperability: The pyecore resource loader will not load the model if the child lacks the xsi:type attribute. Which is the case for model instances serialized by either Eclipse or emf4cpp.
We get the following exception backtrace:

File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 60, in load
    self._decode_eobject(child, modelroot)
  File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 148, in _decode_eobject
    eobject_info = self._decode_node(parent_eobj, current_node)
  File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 230, in _decode_node
    eobject = etype()
TypeError: 'EProxy' object is not callable

Kind regards

**Comment by aranega** [comment] 2019-10-07 13:50
Hi @stefanq 

Thanks a lot for the issue and the bug you found. It sounds like a serious issue, I'll watch it as soon as possible. That must be a special case because usually, PyEcore doesn't care so much about the `xsi:type` and generates it only if the target class of the `EReference` doen't match the one from the object being serialized.
Could you add a minimal example about your case? It would really help me being for sure in the same context you are.

**Comment by stefanq** [comment] 2019-10-14 08:56
Hi Vincent,

thanks for your quick answer.
I prepared a demonstration of the issue for you (sorry, this took a little longer as by extracting a minimal example from our source-base I had to relearn certain things (in particular not forgetting to register at the metamodel registry)).

Regarding caring about xsi:type, we observe that an XMI serialized by PyEcore usually has such an attribute only if necessary for disambiguation, as you say and in accordance with the XMI standard.
However, the attached meta model demonstrates a case, where the PyEcore expects one for a non-ambiguous case.

Find attached
- a trivial meta model given by two Ecore files,
- a simple model eclipse.root.xmi, serialized form within Eclipse,
- a PyEcore/Python script creating the same model but yielding a slightly different XMI serialization, for comparison.
[issue72-demo.zip](https://github.com/pyecore/pyecore/files/3723656/issue72-demo.zip)

Actually, apart from the xsi:type attribute, there is a second relevant difference in XMI serialization, which is the xmlns:model='model' XML namespace declaration which the Java XMI serialization is lacking.

Kind regards
Stefan

**Comment by aranega** [comment] 2019-10-14 09:09
Wow, thanks a lot @stefanq ! On my side, I looked and identified some parts from where the problem could come from. I take a look to your code asap!

**Comment by aranega** [comment] 2019-10-16 09:47
Hi @stefanq , I had a little bit of time to work on the issue. I fixed the problems you presented, it was mainly related to the fact that some `EProxy` were not reacting the right way. I pushed the fix on a branch `feature/issue72` at the moment, I'll integrate your minimal example as a non regression test as soon as possible.

Thanks again a lot for the issue and the example!

**Comment by stefanq** [comment] 2019-10-16 13:51
> Thanks again a lot for the issue and the example!
You're welcome.
While you mention it, regarding my difficulties with providing this little example I'd have a suggestion: 
PyEcore comes with comprehensive and high quality documentation, with much emphasis on creating, navigating and modifying meta models and models.
However, the more simple (but even valuable) use case implemented in my example script, i.e. pulling an existing metamodel and exposing its hierarchy of Ecore packages in Python in a convenient way (i.e. by using EDynamicPackage and ideally with a single entry point (given by the root package)) is not well covered. At least not in one place.
Therefore, I could imagine that providing a introductory chapter on this topic would be quite useful for people who just want to quickly provide a Python extension of an existing Ecore metamodel (or do model transformation with existing metamodels).

Thanks for resolving this so quickly!

**Comment by aranega** [comment] 2019-10-24 08:11
Hi @stefanq I pushed a new version yesterday `0.11.1`, I forgot to tell you. I pushed tests and everything sounds good. Tell me if it works for you

**Comment by aranega** [comment] 2019-11-19 07:13
> However, the more simple (but even valuable) use case implemented in my example script, i.e. pulling an existing metamodel and exposing its hierarchy of Ecore packages in Python in a convenient way (i.e. by using EDynamicPackage and ideally with a single entry point (given by the root package)) is not well covered. At least not in one place.
> Therefore, I could imagine that providing a introductory chapter on this topic would be quite useful for people who just want to quickly provide a Python extension of an existing Ecore metamodel (or do model transformation with existing metamodels).

@stefanq I just read your message, I must change my eyes, I totally missed it... You are right, the documentation is really feature oriented, but a chapter or two use case oriented would be very profitable. I'll try to add that for next release and I'll probably integreate the kind of text I wrote about generating the `notation` metamodel from GMF that implies somes manual modifications.

**Closed** 2020-03-02 15:01 UTC
