### ISSUE TITLE
Issue with serializing EString EAttributes with upperBound="-1"

### ISSUE THREAD

**Issue by TerryKingston** [pyecore/pyecore#26] opened 2018-06-22 17:20 UTC
Hello @aranega 

It appears there is an issue with serializing EAttributes which are a list of strings. 
For example, in testing with the following EClass EAttribute
```
<eStructuralFeatures xsi:type="ecore:EAttribute" 
  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" 
  upperBound="-1" 
  name="myStringList"/>
```
In a resource generated based on the metamodel, the attribute is an EOrderedSet (because of the upperBound="-1") which is good, then strings are added to it and then the resource is saved, resulting in:

```
<myClass
  ...
  myStringList="E O r d e r e d S e t ( [ ' s t r i n g    o n e ' ,   ' s t r i n g   t w o ' , ] )"
```

There's always the possibility that I'm just doing it wrong, But this brings the question of the correct way of defining a list of strings in XML. It appears the string values, specifying the xmi:ids, are space-delimited on the EResource attributes. I'm guessing the space-delimination is probably also being applied here. Does mean EString EAttributes should have escaped space characters when they are not meant to delimit strings in the list? Please help me understand the correct way to add a list of string values in the XML.

Thanks,

**Comment by aranega** [comment] 2018-06-22 17:30
Hi @TerryKingston,

Thanks a lot for the report. Once again, everything's fine on your side, the behavior you have is actually a regression. I'm on it!

**Comment by CFAndy** [comment] 2018-06-25 07:17
Hello @aranega 
Also a great fix for me. 
A small issue here: Following XMI file(text is empty) will trigger a exception in xmi.py due to node.text is None. 
<myClass>
  <myStringList></myStringList>
  <myStringList></myStringList>
</myClass>
 File "Anaconda3\lib\site-packages\pyecore\resources\xmi.py", in _decode_node
    eobject = etype()
TypeError: 'EDataType' object is not callable.
If I hard code it to do attribute decoding, it can work. But do you think we could have a more elegent solution for such corner case?
again, great progress.
-Andy

**Comment by aranega** [comment] 2018-06-25 07:28
Hi @CFAndy, I'm really sorry about this, I totally forgot this corner case in my test cases. I think I know where I can deal with this in a kind of transparent way, I will provide a fix asap and release a new version during my lunch break!

@CFAndy @TerryKingston Thanks a lot for your issues reports!

**Comment by aranega** [comment] 2018-06-25 10:32
@CFAndy I pushed a fix on the `develop` branch with updated test cases. I apologize for asking, but could you test the `develop` branch on your test data set? I also covered 'whitespace only' strings but perhaps there is other corner cases I forgot. If you have no time, don't worry, I will release a new version and fix again if needed.

**Comment by CFAndy** [comment] 2018-06-26 00:31
@aranega 
I manually merged your fix in xmi.py.  it works like a charm! Please release it! 
-Andy

**Comment by aranega** [comment] 2018-06-26 05:01
@CFAndy Thanks a lot for the manual testing on your side! The new version: `0.8.4` is released on pypi.

**Comment by stefanq** [comment] 2021-01-24 18:42
I'm not satisfied with the resolution because there are cases not covered, as
- empty strings
- duplicate strings (the internal representation seems to be a set!)

**Comment by aranega** [comment] 2021-01-24 20:25
Hi @stefanq

Thanks for your issue! 
Regarding the duplicated strings, by default `EAttribute` (and `EReference`) are considered `unique` and `ordered`, consequently, they are implemented by an ordered set. To change that, you need to pass an option to the `EAttribute`.

For example, for a "static-like" metamodel:

```python
@EMetaclass
class A(object):
    names = EAttribute(eType=EString, upper=-1, unique=False)

inst = A()
inst.names.append("abc")
inst.names.append("abc")
```

Regarding empty-strings, this is the default behavior of collection in EMF-Java, it takes empty-strings and null elements. You made me really doubt :p so I checked again an EMF Java, you can find the test I used [on this repl.it receipe](https://repl.it/@aranega/InfatuatedEarnestEngine#Main.java)

the equivalent Python code with PyEcore would be this one (in a full dynamic metamodel fashion like in the EMF-Java version):

```python
from pyecore.ecore import EClass, EAttribute, EString

A = EClass('A')
A.eStructuralFeatures.append(EAttribute('names', eType=EString, upper=-1, unique=False))
A.eStructuralFeatures.append(EAttribute('names2', eType=EString, upper=-1))

inst = A()
inst.names.append("a")
inst.names.append("a")
inst.names.append("")
inst.names.append(None)
print(f"Names={inst.names}")

inst.names2.append("a")
inst.names2.append("a")
inst.names2.append("")
inst.names2.append(None)
print(f"Names2={inst.names2}")
```

**Comment by stefanq** [comment] 2021-01-28 15:23
Hello Vincent,

thanks for promptly reacting on this.
Regarding the first issue we indeed have a lacking `unique=false` on an `EAttribute` in our Ecore meta model.
Regarding the second issue you demonstrate that there is no problem with the runtime representation of empty strings. However, my problem is when writing this to file: In this case an alternative serialization format as a space delimited single string is used for the attribute value in XML and there of course an empty sting cannot be represented!
Kind regards

**Comment by aranega** [comment] 2021-01-28 18:01
Hi @stefanq 

Aaaah, yes, sorry I misunderstood your message. You're right, I should handle thoses cases in the XMI as I do for null references. I will try to do that asap! 
Sorry again for the misunderstanding

**Comment by stefanq** [comment] 2021-01-28 18:12
Yeah, as the summary already says: it's all about serialization :-D
And so should be the test cases.
Don't mind, this is not much of a problem for me/us as we are still in very early stages of rolling this out to customers... ;-)

**Comment by aranega** [comment] 2021-01-28 18:42
> Yeah, as the summary already says: it's all about serialization :-D

... totally my fault, I jumped into conclusion. I was doubting so much about the runtime implementation (and had so much trouble while doing a new setup for EMF/Java/Eclipse) that I misread. Sorry again :sweat_smile: 

I had a little bit of time so I fixed it on `develop`, you can check it out and tell me if it's right for you. I will try to do a quick release soon.

**Comment by aranega** [comment] 2023-11-01 08:38
Fixed since few versions

**Closed by aranega** 2023-11-01 08:38 UTC
Labels: bug
